# Generated by Django 2.2.6 on 2019-10-17 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=80)),
                ('associados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
                ('nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=80)),
                ('academias', models.ManyToManyField(related_name='usuarios', to='clients.Academia')),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('contato', models.TextField()),
                ('academia', models.ManyToManyField(related_name='transportes', to='clients.Academia')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='clients.Academia')),
                ('compradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='clients.User')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
                ('incluso', models.TextField()),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='clients.Academia')),
                ('compradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='clients.User')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('segunda_e', models.TimeField()),
                ('segunda_s', models.TimeField()),
                ('terca_e', models.TimeField()),
                ('terca_s', models.TimeField()),
                ('quarta_e', models.TimeField()),
                ('quarta_s', models.TimeField()),
                ('quinta_e', models.TimeField()),
                ('quinta_s', models.TimeField()),
                ('sexta_e', models.TimeField()),
                ('sexta_s', models.TimeField()),
                ('sabado_e', models.TimeField()),
                ('sabado_s', models.TimeField()),
                ('domingo_e', models.TimeField()),
                ('domingo_s', models.TimeField()),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clients.Academia')),
                ('planos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clients.Plano')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira', models.CharField(max_length=15)),
                ('numero', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='clients.User')),
            ],
        ),
    ]
